spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.48.11:4406/cloud_book_ticket?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
