server:
  port: 8101
spring:
  datasource:
    druid:
      name: cloud_book_ticket
      url: jdbc:mysql://localhost:3306/cloud_book_ticket?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 500
      enable: true
      db-type: mysql

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.tanfuhua.model
  type-enums-package: org.tanfuhua.enums

# 记录dao层SQL执行日志
logging:
  level:
    org.tanfuhua.dao: debug
    org.tanfuhua.client: debug
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
kyfw:
  codeServer: http://10.211.55.5:8080/verify/base64/
app:
  kyfw-url: https://www.12306.cn/index/
  web-driver-wait-second: 6
  user-agent-list:
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
    - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
  chrome-driver-path: /Users/gaofubo/Software/Mac/chromedriver_mac64/chromedriver_111.0.5563.64
  selenium-map:
    source: "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
  chrome-option-list:
    - "--remote-allow-origins=*"
    - "disable-infobars"
    - "--disable-gpu"
#    - "blink-settings=imagesEnabled=false"
#    - "--headless"
  kyfw-url-referer-map:
    "/otn/login/conf": "https://www.12306.cn/index/index.html"
    "/otn/resources/js/framework/station_name.js": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/leftTicket/query": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/login/checkUser": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/leftTicket/submitOrderRequest": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/confirmPassenger/initDc": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/confirmPassenger/getPassengerDTOs": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/checkOrderInfo": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/getQueueCount": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/confirmSingleForQueue": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/queryOrderWaitTime": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/resultOrderForDcQueue": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
