server:
  port: 8101
  servlet:
    session:
      timeout: 3600s
spring:
  datasource:
    druid:
      name: cloud_book_ticket
      url: jdbc:mysql://localhost:3306/cloud_book_ticket?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 500
      enable: true
      db-type: mysql

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.tanfuhua.model
  type-enums-package: org.tanfuhua.enums

# 记录dao层SQL执行日志
logging:
  level:
    org.tanfuhua.dao: debug
    org.tanfuhua.client: debug
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
lowcode:
  id: 1
  username: admin
  password: 123456
  schema: "{\"version\":\"1.0.0\",\"componentsMap\":[{\"devMode\":\"lowCode\",\"componentName\":\"Page\"}],\"componentsTree\":[{\"componentName\":\"Page\",\"id\":\"node_dockcviv8fo1\",\"props\":{\"ref\":\"outerView\",\"style\":{\"height\":\"100%\"}},\"docId\":\"doclaqkk3b9\",\"fileName\":\"/\",\"dataSource\":{\"list\":[{\"type\":\"fetch\",\"isInit\":true,\"options\":{\"params\":{},\"method\":\"GET\",\"isCors\":true,\"timeout\":5000,\"headers\":{},\"uri\":\"mock/info.json\"},\"id\":\"info\",\"shouldFetch\":{\"type\":\"JSFunction\",\"value\":\"function() { \\n  console.log('should fetch.....');\\n  return true; \\n}\"}}]},\"state\":{\"text\":{\"type\":\"JSExpression\",\"value\":\"\\\"outer\\\"\"},\"isShowDialog\":{\"type\":\"JSExpression\",\"value\":\"false\"}},\"css\":\"\",\"lifeCycles\":{\"componentDidMount\":{\"type\":\"JSFunction\",\"value\":\"function componentDidMount() {\\n  console.log('did mount');\\n}\",\"source\":\"function componentDidMount() {\\n  console.log('did mount');\\n}\"},\"componentWillUnmount\":{\"type\":\"JSFunction\",\"value\":\"function componentWillUnmount() {\\n  console.log('will unmount');\\n}\",\"source\":\"function componentWillUnmount() {\\n  console.log('will unmount');\\n}\"}},\"methods\":{\"getHelloWorldText\":{\"type\":\"JSFunction\",\"value\":\"function getHelloWorldText() {\\n  return this.i18n('i18n-jwg27yo4');\\n}\",\"source\":\"function getHelloWorldText() {\\n  return this.i18n('i18n-jwg27yo4');\\n}\"},\"getHelloWorldText2\":{\"type\":\"JSFunction\",\"value\":\"function getHelloWorldText2() {\\n  return this.i18n('i18n-jwg27yo3', {\\n    name: '絮黎'\\n  });\\n}\",\"source\":\"function getHelloWorldText2() {\\n  return this.i18n('i18n-jwg27yo3', {\\n    name: '絮黎'\\n  });\\n}\"}},\"originCode\":\"class LowcodeComponent extends Component {\\n  state = {\\n    \\\"text\\\": \\\"outer\\\",\\n    \\\"isShowDialog\\\": false\\n  }\\n  componentDidMount() {\\n    console.log('did mount');\\n  }\\n  componentWillUnmount() {\\n    console.log('will unmount');\\n  }\\n  // 国际化\\n  getHelloWorldText() {\\n    return this.i18n('i18n-jwg27yo4');\\n  }\\n  getHelloWorldText2() {\\n    return this.i18n('i18n-jwg27yo3', {\\n      name: '絮黎',\\n    });\\n  }\\n}\",\"hidden\":false,\"title\":\"\",\"isLocked\":false,\"condition\":true,\"conditionGroup\":\"\"}],\"i18n\":{\"zh-CN\":{\"i18n-jwg27yo4\":\"你好 \",\"i18n-jwg27yo3\":\"{name} 博士\"},\"en-US\":{\"i18n-jwg27yo4\":\"Hello \",\"i18n-jwg27yo3\":\"Doctor {name}\"}}}"
  packages: "[{\"package\":\"moment\",\"version\":\"2.24.0\",\"urls\":[\"https://g.alicdn.com/mylib/moment/2.24.0/min/moment.min.js\"],\"library\":\"moment\"},{\"package\":\"lodash\",\"library\":\"_\",\"urls\":[\"https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js\"]},{\"title\":\"fusion组件库\",\"package\":\"@alifd/next\",\"version\":\"1.26.4\",\"urls\":[\"https://g.alicdn.com/code/lib/alifd__next/1.26.4/next.min.css\",\"https://g.alicdn.com/code/lib/alifd__next/1.26.4/next-with-locales.min.js\"],\"library\":\"Next\"},{\"title\":\"NextTable\",\"package\":\"NextTable\",\"version\":\"1.0.1\",\"urls\":[\"https://g.alicdn.com/fusion-platform/pro-table/1.0.1/next-table.js\",\"https://g.alicdn.com/fusion-platform/pro-table/1.0.1/next-table.css\"],\"library\":\"NextTable\"},{\"package\":\"@alilc/lowcode-materials\",\"version\":\"1.1.0\",\"library\":\"AlilcLowcodeMaterials\",\"urls\":[\"https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.1.0/dist/AlilcLowcodeMaterials.js\",\"https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.1.0/dist/AlilcLowcodeMaterials.css\"],\"editUrls\":[\"https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.1.0/build/lowcode/view.js\",\"https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.1.0/build/lowcode/view.css\"]},{\"package\":\"@alifd/layout\",\"version\":\"2.0.7\",\"library\":\"AlifdLayout\",\"urls\":[\"https://alifd.alicdn.com/npm/@alifd/layout@2.0.7/dist/AlifdLayout.js\",\"https://alifd.alicdn.com/npm/@alifd/layout@2.0.7/dist/AlifdLayout.css\"],\"editUrls\":[\"https://alifd.alicdn.com/npm/@alifd/layout@2.0.7/build/lowcode/view.js\",\"https://alifd.alicdn.com/npm/@alifd/layout@2.0.7/build/lowcode/view.css\"]},{\"package\":\"@alifd/fusion-ui\",\"version\":\"2.0.0\",\"library\":\"AlifdFusionUi\",\"urls\":[\"https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.0/dist/AlifdFusionUi.js\",\"https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.0/dist/AlifdFusionUi.css\"],\"editUrls\":[\"https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.0/build/lowcode/view.js\",\"https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.0/build/lowcode/view.css\"]}]"

app:
  kyfw-url: https://kyfw.12306.cn/otn/view/index.html
  codeServer: http://10.211.55.5:8080/verify/base64/
  web-driver-fast-wait-second: 1
  web-driver-slow-wait-second: 10
  check-submit-order-wait-second: 5
  user-agent-list:
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
    - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
  chrome-driver-path: /driver/chrome/mac/chromedriver_112.0.5615.49
  selenium-map:
    source: "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
  chrome-option-list:
    - "--remote-allow-origins=*"
    - "disable-infobars"
    - "--disable-gpu"
    - "blink-settings=imagesEnabled=false"
#    - "--headless"
  kyfw-url-referer-map:
    "/otn/login/conf": "https://www.12306.cn/index/index.html"
    "/otn/resources/js/framework/station_name.js": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/leftTicket/query": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/login/checkUser": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/leftTicket/submitOrderRequest": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/confirmPassenger/initDc": "https://kyfw.12306.cn/otn/leftTicket/init"
    "/otn/confirmPassenger/getPassengerDTOs": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/checkOrderInfo": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/getQueueCount": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/confirmSingleForQueue": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/queryOrderWaitTime": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
    "/otn/confirmPassenger/resultOrderForDcQueue": "https://kyfw.12306.cn/otn/confirmPassenger/initDc"
